name: solution_challenge_project
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  cupertino_icons: ^1.0.2
  flutter_svg:
  circular_seek_bar: ^1.1.0+2
  google_maps_flutter:
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+1
  firebase_core:
  flutter_animation_progress_bar: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
    - family: OpenSans-Medium
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
    - family: PlayfairDisplay-Medium
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Medium.ttf
    - family: PlayfairDisplay-Regular
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
    - family: PlayfairDisplay-SemiBold
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-SemiBold.ttf
    

