// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmL_mzK1eZfevqjZEsv1VmmteyKd53pHw',
    appId: '1:483025946890:web:99fda56b518ff4fc8ed2f3',
    messagingSenderId: '483025946890',
    projectId: 'solution-challenge-proje-a0914',
    authDomain: 'solution-challenge-proje-a0914.firebaseapp.com',
    storageBucket: 'solution-challenge-proje-a0914.appspot.com',
    measurementId: 'G-6VSDXV8DZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_AvskkJzRL3cAYmL3tqAqByR9VbAze5k',
    appId: '1:483025946890:android:ad996f6da79306a68ed2f3',
    messagingSenderId: '483025946890',
    projectId: 'solution-challenge-proje-a0914',
    storageBucket: 'solution-challenge-proje-a0914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrpmuUdvmQm8JhsxLw8tTh6mLEM3lVCp8',
    appId: '1:483025946890:ios:b1e395e1b5c250308ed2f3',
    messagingSenderId: '483025946890',
    projectId: 'solution-challenge-proje-a0914',
    storageBucket: 'solution-challenge-proje-a0914.appspot.com',
    iosClientId: '483025946890-oedssu91nus8np3fd80agdhhe639f4pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.solutionChallengeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrpmuUdvmQm8JhsxLw8tTh6mLEM3lVCp8',
    appId: '1:483025946890:ios:b1e395e1b5c250308ed2f3',
    messagingSenderId: '483025946890',
    projectId: 'solution-challenge-proje-a0914',
    storageBucket: 'solution-challenge-proje-a0914.appspot.com',
    iosClientId: '483025946890-oedssu91nus8np3fd80agdhhe639f4pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.solutionChallengeProject',
  );
}
